package audio.switchboard.voicemodlocalplayback.utils

val voices = listOf(
    "alice",
    "alien",
    "baby",
    "belcher",
    "blocks",
    "bob",
    "cartoon-man",
    "cartoon-woman",
    "cave",
    "dark",
    "deep",
    "fire-dragon",
    "gas-mask",
    "genki",
    "ghost",
    "magic-chords",
    "mothership",
    "mr-x",
    "out-of-range",
    "pilot",
    "radio-demon",
    "robot",
    "runic-sorceress",
    "space-trooper",
    "speechifier",
    "the-billionhair",
    "the-demon",
    "the-narrator",
    "trailer-guy",
    "trap-tune",
    "trauma-medic",
    "uncle-in-chief",
    "voicelab"
)